// Code generated by packages/protoc_ex.run_Gen_Go_PoolMethod DO NOT EDIT.
package pb
import (
	"sync"
	"zserviceapps/packages/zservice"
)


// ---------------------------------------- run_Gen_Go_PoolMethod => 👇 FileName: etcdservice.pb.go

// EventBody 消息池
var pool_EventBody = &sync.Pool{
    New: func() any {
        msg:= &EventBody{}
        pool_EventBody_IsPoolMap.Store(msg,false)
        return msg
    },
}

// EventBody 消息池 是否在池中
var pool_EventBody_IsPoolMap = &sync.Map{}

// 回收 EventBody 消息
func (x *EventBody) Put() {
	put_EventBody(x)
}

// 回收 EventBody 消息 并返回数据字节内容
func (x *EventBody) Put_Bytes() []byte {
	defer put_EventBody(x)
	return x.ToBytes()
}

// 回收 EventBody 消息 并返回数据 json 内容
func (x *EventBody) Put_Json() string {
	defer put_EventBody(x)
	return x.ToJson()
}

// 从对象池中获取 EventBody 消息
func Get_EventBody() *EventBody {
    msg := pool_EventBody.Get().(*EventBody)
	pool_EventBody_IsPoolMap.Store(msg, false)
	return msg
}

// 回收 EventBody 消息
func put_EventBody(msg *EventBody) {
    if msg == nil {
        return
    }

    if v,has := pool_EventBody_IsPoolMap.Load(msg); has && v.(bool) {
        zservice.LogErrorCaller(3,"pb.Heartbeat_Info is in pool")
        return
    }
    
    
    
    msg.Ctx=""
    
    msg.Body=nil

    
	pool_EventBody_IsPoolMap.Store(msg, true)
    pool_EventBody.Put(msg)
}
	
// 转换为 []byte
func (x *EventBody) ToBytes() []byte {
	return zservice.ProtobufMustMarshal(x)
}

// 转换为 json 字符串
func (x *EventBody) ToJson() string {
	return zservice.JsonMustMarshalString(x)
}// ---------------------------------------- run_Gen_Go_PoolMethod => 👆 FileName: etcdservice.pb.go



// ---------------------------------------- run_Gen_Go_FieldMethod => 👇 FileName: etcdservice.pb.go

// 设置 Ctx.string 字段值
func (x *EventBody) SetCtx(v string)*EventBody {
    x.Ctx = v
    return x
}

// 设置 Body.[]byte 字段值
func (x *EventBody) SetBody(v []byte)*EventBody {
    x.Body = v
    return x
}
// ---------------------------------------- run_Gen_Go_FieldMethod => 👆 FileName: etcdservice.pb.go



// ---------------------------------------- run_Gen_Go_CloneMethod => 👇 FileName: etcdservice.pb.go

// 克隆 EventBody
func (x *EventBody) Clone() *EventBody {
    clone := Get_EventBody()

    clone.SetCtx(x.Ctx)
    clone.SetBody(x.Body)

    return clone
}
// ---------------------------------------- run_Gen_Go_CloneMethod => 👆 FileName: etcdservice.pb.go



// ---------------------------------------- run_Gen_Go_AddMethod => 👇 FileName: etcdservice.pb.go

// 添加一个 byte
func (x *EventBody) AddOneBody(v byte) *EventBody {
    x.Body = append(x.Body, v)
    return x
}
// ---------------------------------------- run_Gen_Go_AddMethod => 👆 FileName: etcdservice.pb.go

