
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package luban;


type TbLuban struct {
    _dataMap map[int32]*Luban
    _dataList []*Luban
}

func NewTbLuban(_buf []map[string]interface{}) (*TbLuban, error) {
    _dataList := make([]*Luban, 0, len(_buf))
    dataMap := make(map[int32]*Luban)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLuban(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &TbLuban{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbLuban) GetDataMap() map[int32]*Luban {
    return table._dataMap
}

func (table *TbLuban) GetDataList() []*Luban {
    return table._dataList
}

func (table *TbLuban) Get(key int32) *Luban {
    return table._dataMap[key]
}


