name: build_service_image

on: 
  push: 
    tags:
      - "*/*"

jobs:
  build:
    container:
      image: catthehacker/ubuntu:act-22.04
      deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: "1G"
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branches | 分支拉取
        uses: http://git.246.local/actions/checkout@v4
      - name: Docker Build | 镜像打包
        run: |
          echo '
          #!/bin/bash
          # 参数准备
          refPath=$1
          tagName=${refPath/refs\/tags\//}
          serviceName=${tagName/\/*/}
          image=${tagName/\//:}
          image=$(echo $image | tr A-Z a-z)
          dockerCLI="docker build --tag zservice/$image --build-arg="SERVERNAME=$serviceName" ."

          # 输出相关消息
          echo "RefPath:      $refPath"
          echo "TagName:      $tagName"
          echo "ServiceName:  $serviceName"
          echo "Image:        $image"
          echo "Docker CLI:   $dockerCLI"

          $dockerCLI
          ' > build.sh
          bash ./build.sh ${{ gitea.ref }}