// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: zsms.proto

package zsms_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Default_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"` // 服务状态码 约定: 1 表示成功, 其它数字根据业务进行返回
}

func (x *Default_RES) Reset() {
	*x = Default_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zsms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Default_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Default_RES) ProtoMessage() {}

func (x *Default_RES) ProtoReflect() protoreflect.Message {
	mi := &file_zsms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Default_RES.ProtoReflect.Descriptor instead.
func (*Default_RES) Descriptor() ([]byte, []int) {
	return file_zsms_proto_rawDescGZIP(), []int{0}
}

func (x *Default_RES) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type SendVerifyCode_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone  string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`   // 手机号 必须带有 +86
	Serive string `protobuf:"bytes,2,opt,name=Serive,proto3" json:"Serive,omitempty"` // 服务标识，哪个服务发起的验证码请求，可以为空字符串
}

func (x *SendVerifyCode_REQ) Reset() {
	*x = SendVerifyCode_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zsms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVerifyCode_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerifyCode_REQ) ProtoMessage() {}

func (x *SendVerifyCode_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_zsms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerifyCode_REQ.ProtoReflect.Descriptor instead.
func (*SendVerifyCode_REQ) Descriptor() ([]byte, []int) {
	return file_zsms_proto_rawDescGZIP(), []int{1}
}

func (x *SendVerifyCode_REQ) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendVerifyCode_REQ) GetSerive() string {
	if x != nil {
		return x.Serive
	}
	return ""
}

type VerifyCode_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone  string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`   // 手机号 必须带有 +86
	Serive string `protobuf:"bytes,2,opt,name=Serive,proto3" json:"Serive,omitempty"` // 服务标识，哪个服务发起的验证码请求，可以为空字符串
	Code   string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`     // 验证码
}

func (x *VerifyCode_REQ) Reset() {
	*x = VerifyCode_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zsms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCode_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCode_REQ) ProtoMessage() {}

func (x *VerifyCode_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_zsms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCode_REQ.ProtoReflect.Descriptor instead.
func (*VerifyCode_REQ) Descriptor() ([]byte, []int) {
	return file_zsms_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCode_REQ) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifyCode_REQ) GetSerive() string {
	if x != nil {
		return x.Serive
	}
	return ""
}

func (x *VerifyCode_REQ) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_zsms_proto protoreflect.FileDescriptor

var file_zsms_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x7a, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x7a, 0x73,
	0x6d, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x21, 0x0a, 0x0b, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x5f, 0x52, 0x45, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x42, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x72, 0x69, 0x76, 0x65, 0x22, 0x52, 0x0a, 0x0e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x72, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x32, 0x88, 0x01, 0x0a, 0x04, 0x7a, 0x73, 0x6d, 0x73, 0x12, 0x43, 0x0a, 0x0e, 0x53, 0x65, 0x6e,
	0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x2e, 0x7a, 0x73,
	0x6d, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x5f, 0x52, 0x45, 0x51, 0x1a, 0x14, 0x2e, 0x7a, 0x73, 0x6d, 0x73, 0x5f,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x3b,
	0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x7a,
	0x73, 0x6d, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x5f, 0x52, 0x45, 0x51, 0x1a, 0x14, 0x2e, 0x7a, 0x73, 0x6d, 0x73, 0x5f, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x52, 0x45, 0x53, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x7a, 0x73, 0x6d, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zsms_proto_rawDescOnce sync.Once
	file_zsms_proto_rawDescData = file_zsms_proto_rawDesc
)

func file_zsms_proto_rawDescGZIP() []byte {
	file_zsms_proto_rawDescOnce.Do(func() {
		file_zsms_proto_rawDescData = protoimpl.X.CompressGZIP(file_zsms_proto_rawDescData)
	})
	return file_zsms_proto_rawDescData
}

var file_zsms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zsms_proto_goTypes = []interface{}{
	(*Default_RES)(nil),        // 0: zsms_pb.Default_RES
	(*SendVerifyCode_REQ)(nil), // 1: zsms_pb.SendVerifyCode_REQ
	(*VerifyCode_REQ)(nil),     // 2: zsms_pb.VerifyCode_REQ
}
var file_zsms_proto_depIdxs = []int32{
	1, // 0: zsms_pb.zsms.SendVerifyCode:input_type -> zsms_pb.SendVerifyCode_REQ
	2, // 1: zsms_pb.zsms.VerifyCode:input_type -> zsms_pb.VerifyCode_REQ
	0, // 2: zsms_pb.zsms.SendVerifyCode:output_type -> zsms_pb.Default_RES
	0, // 3: zsms_pb.zsms.VerifyCode:output_type -> zsms_pb.Default_RES
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zsms_proto_init() }
func file_zsms_proto_init() {
	if File_zsms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zsms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Default_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zsms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVerifyCode_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zsms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCode_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zsms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zsms_proto_goTypes,
		DependencyIndexes: file_zsms_proto_depIdxs,
		MessageInfos:      file_zsms_proto_msgTypes,
	}.Build()
	File_zsms_proto = out.File
	file_zsms_proto_rawDesc = nil
	file_zsms_proto_goTypes = nil
	file_zsms_proto_depIdxs = nil
}
