// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: zconfig.proto

package zconfig_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Default_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"` // 服务状态码 约定: 1 表示成功, 其它数字根据业务进行返回
}

func (x *Default_RES) Reset() {
	*x = Default_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Default_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Default_RES) ProtoMessage() {}

func (x *Default_RES) ProtoReflect() protoreflect.Message {
	mi := &file_zconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Default_RES.ProtoReflect.Descriptor instead.
func (*Default_RES) Descriptor() ([]byte, []int) {
	return file_zconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Default_RES) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetFileConfig_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"` // 文件名
	Keys     string `protobuf:"bytes,2,opt,name=Keys,proto3" json:"Keys,omitempty"`         // key 需要返回哪些值, 空值返回全部
}

func (x *GetFileConfig_REQ) Reset() {
	*x = GetFileConfig_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileConfig_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileConfig_REQ) ProtoMessage() {}

func (x *GetFileConfig_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_zconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileConfig_REQ.ProtoReflect.Descriptor instead.
func (*GetFileConfig_REQ) Descriptor() ([]byte, []int) {
	return file_zconfig_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileConfig_REQ) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetFileConfig_REQ) GetKeys() string {
	if x != nil {
		return x.Keys
	}
	return ""
}

type GetFileConfig_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  uint32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`  // 服务状态码 约定: 1 表示成功, 其它数字根据业务进行返回
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 返回的数据, 返回的是一个 json 数组
}

func (x *GetFileConfig_RES) Reset() {
	*x = GetFileConfig_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileConfig_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileConfig_RES) ProtoMessage() {}

func (x *GetFileConfig_RES) ProtoReflect() protoreflect.Message {
	mi := &file_zconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileConfig_RES.ProtoReflect.Descriptor instead.
func (*GetFileConfig_RES) Descriptor() ([]byte, []int) {
	return file_zconfig_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileConfig_RES) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetFileConfig_RES) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_zconfig_proto protoreflect.FileDescriptor

var file_zconfig_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x7a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x7a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x62, 0x22, 0x21, 0x0a, 0x0b, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x52, 0x45, 0x51, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b,
	0x65, 0x79, 0x73, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0x58, 0x0a, 0x07, 0x7a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4d, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d,
	0x2e, 0x7a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x52, 0x45, 0x51, 0x1a, 0x1d, 0x2e,
	0x7a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x52, 0x45, 0x53, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x2f, 0x7a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zconfig_proto_rawDescOnce sync.Once
	file_zconfig_proto_rawDescData = file_zconfig_proto_rawDesc
)

func file_zconfig_proto_rawDescGZIP() []byte {
	file_zconfig_proto_rawDescOnce.Do(func() {
		file_zconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_zconfig_proto_rawDescData)
	})
	return file_zconfig_proto_rawDescData
}

var file_zconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zconfig_proto_goTypes = []interface{}{
	(*Default_RES)(nil),       // 0: zconfig_pb.Default_RES
	(*GetFileConfig_REQ)(nil), // 1: zconfig_pb.GetFileConfig_REQ
	(*GetFileConfig_RES)(nil), // 2: zconfig_pb.GetFileConfig_RES
}
var file_zconfig_proto_depIdxs = []int32{
	1, // 0: zconfig_pb.zconfig.GetFileConfig:input_type -> zconfig_pb.GetFileConfig_REQ
	2, // 1: zconfig_pb.zconfig.GetFileConfig:output_type -> zconfig_pb.GetFileConfig_RES
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zconfig_proto_init() }
func file_zconfig_proto_init() {
	if File_zconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Default_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileConfig_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileConfig_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zconfig_proto_goTypes,
		DependencyIndexes: file_zconfig_proto_depIdxs,
		MessageInfos:      file_zconfig_proto_msgTypes,
	}.Build()
	File_zconfig_proto = out.File
	file_zconfig_proto_rawDesc = nil
	file_zconfig_proto_goTypes = nil
	file_zconfig_proto_depIdxs = nil
}
