// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: zauth.proto

package zauth_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Zauth_LoginByPhone_FullMethodName = "/zauth_pb.zauth/LoginByPhone"
	Zauth_CheckAuth_FullMethodName    = "/zauth_pb.zauth/CheckAuth"
)

// ZauthClient is the client API for Zauth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZauthClient interface {
	LoginByPhone(ctx context.Context, in *LoginByPhone_REQ, opts ...grpc.CallOption) (*Default_RES, error)
	CheckAuth(ctx context.Context, in *CheckAuth_REQ, opts ...grpc.CallOption) (*CheckAuth_RES, error)
}

type zauthClient struct {
	cc grpc.ClientConnInterface
}

func NewZauthClient(cc grpc.ClientConnInterface) ZauthClient {
	return &zauthClient{cc}
}

func (c *zauthClient) LoginByPhone(ctx context.Context, in *LoginByPhone_REQ, opts ...grpc.CallOption) (*Default_RES, error) {
	out := new(Default_RES)
	err := c.cc.Invoke(ctx, Zauth_LoginByPhone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zauthClient) CheckAuth(ctx context.Context, in *CheckAuth_REQ, opts ...grpc.CallOption) (*CheckAuth_RES, error) {
	out := new(CheckAuth_RES)
	err := c.cc.Invoke(ctx, Zauth_CheckAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZauthServer is the server API for Zauth service.
// All implementations must embed UnimplementedZauthServer
// for forward compatibility
type ZauthServer interface {
	LoginByPhone(context.Context, *LoginByPhone_REQ) (*Default_RES, error)
	CheckAuth(context.Context, *CheckAuth_REQ) (*CheckAuth_RES, error)
	mustEmbedUnimplementedZauthServer()
}

// UnimplementedZauthServer must be embedded to have forward compatible implementations.
type UnimplementedZauthServer struct {
}

func (UnimplementedZauthServer) LoginByPhone(context.Context, *LoginByPhone_REQ) (*Default_RES, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByPhone not implemented")
}
func (UnimplementedZauthServer) CheckAuth(context.Context, *CheckAuth_REQ) (*CheckAuth_RES, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuth not implemented")
}
func (UnimplementedZauthServer) mustEmbedUnimplementedZauthServer() {}

// UnsafeZauthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZauthServer will
// result in compilation errors.
type UnsafeZauthServer interface {
	mustEmbedUnimplementedZauthServer()
}

func RegisterZauthServer(s grpc.ServiceRegistrar, srv ZauthServer) {
	s.RegisterService(&Zauth_ServiceDesc, srv)
}

func _Zauth_LoginByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByPhone_REQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZauthServer).LoginByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zauth_LoginByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZauthServer).LoginByPhone(ctx, req.(*LoginByPhone_REQ))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zauth_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuth_REQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZauthServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zauth_CheckAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZauthServer).CheckAuth(ctx, req.(*CheckAuth_REQ))
	}
	return interceptor(ctx, in, info, handler)
}

// Zauth_ServiceDesc is the grpc.ServiceDesc for Zauth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zauth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zauth_pb.zauth",
	HandlerType: (*ZauthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginByPhone",
			Handler:    _Zauth_LoginByPhone_Handler,
		},
		{
			MethodName: "CheckAuth",
			Handler:    _Zauth_CheckAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zauth.proto",
}
